default_agent: telecom_agent
agents:
  telecom_agent:
    name: telecom_agent
    entrypoint: src/agentcore_runtime.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: /home/btwitsvoid/Documents/ML Project/agentcore
    aws:
      execution_role: arn:aws:iam::133954051176:role/AmazonBedrockAgentCoreSDKRuntime-ap-south-1-7db1a0f14d
      execution_role_auto_create: false
      account: '133954051176'
      region: ap-south-1
      ecr_repository: 133954051176.dkr.ecr.ap-south-1.amazonaws.com/telecom_agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: telecom_agent-CNF3FDCpvp
      agent_arn: arn:aws:bedrock-agentcore:ap-south-1:133954051176:runtime/telecom_agent-CNF3FDCpvp
      agent_session_id: ec6c6c3e-c2ed-43a3-b892-8c6e59e20b39
    codebuild:
      project_name: bedrock-agentcore-telecom_agent-builder
      execution_role: arn:aws:iam::133954051176:role/AmazonBedrockAgentCoreSDKCodeBuild-ap-south-1-7db1a0f14d
      source_bucket: bedrock-agentcore-codebuild-sources-133954051176-ap-south-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
